### GET Request to Retrieve Products
GET http://localhost:3000/products?offset=1&limit=10

###
GET http://localhost:3000/products/04

###
GET http://localhost:3000/product-range/06

###
GET http://localhost:3000/product-category/04
